version: '3.8'

services:
  patient-db:
    image: postgres:latest
    container_name: patient-db
    environment:
      POSTGRES_PASSWORD: iehtian
      POSTGRES_DB: patient
      POSTGRES_USER: patient_user
    ports:
      - '5433:5432'
    volumes:
      - patient-db-data:/var/lib/postgresql # 改为挂载到 /var/lib/postgresql
    restart: unless-stopped

volumes:
  patient-db-data:
