version: '3.8'

services:
  painter-db:
    image: postgres:latest
    container_name: painter-db
    environment:
      POSTGRES_PASSWORD: iehtian
      POSTGRES_DB: painter
      POSTGRES_USER: painter_user
    ports:
      - '5433:5432'
    volumes:
      - painter-db-data:/var/lib/postgresql # 改为挂载到 /var/lib/postgresql
    restart: unless-stopped

volumes:
  painter-db-data:
